name: qxmledit-brlin # you probably want to 'snapcraft register <name>'
version: latest # just for humans, typically '1.2+git' or '1.3.2'
version-script: git -C parts/qxmledit/src describe --always --dirty --tags
summary: QXmlEdit is a simple XML editor based on Qt libraries. # 79 char long summary
description: |
  QXmlEdit is a simple XML editor based on Qt libraries. Its main features are unusual data visualization modes, nice XML manipulation and presentation and it is multi platform. It can split very big XML files into fragments, and compare XML and XSD files. It was born on Google code (https://code.google.com/p/qxmledit).

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

icon: images/qxmledit.svg

architectures:
  - build-on: i386
    run-on: i386
  - build-on: amd64
    run-on: amd64
  # armhf Not currently buildable due to the following bug:
  # https://github.com/KhronosGroup/OpenGL-Registry/issues/162
  #- build-on: armhf
  #  run-on: armhf
  - build-on: arm64
    run-on: arm64
  - build-on: ppc64el
    run-on: ppc64el
  - build-on: s390x
    run-on: s390x

apps:
  qxmledit-brlin:
    command: desktop-launch $SNAP/bin/qxmledit
    desktop: share/${SNAPCRAFT_PROJECT_NAME}/QXmlEdit.desktop
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - opengl
      - home
      - removable-media

parts:
  qxmledit:
    plugin: qmake
    qt-version: qt5
    options:
      - CONFIG+=release
      - QXMLEDIT_INST_DIR=/snap/$SNAPCRAFT_PROJECT_NAME/current/bin
      - QXMLEDIT_INST_DATA_DIR=/snap/$SNAPCRAFT_PROJECT_NAME/current/share/$SNAPCRAFT_PROJECT_NAME
      - QXMLEDIT_INST_DOC_DIR=/snap/$SNAPCRAFT_PROJECT_NAME/current/share/$SNAPCRAFT_PROJECT_NAME/doc
      - QXMLEDIT_INST_LIB_DIR=/snap/$SNAPCRAFT_PROJECT_NAME/current/lib
      - QXMLEDIT_INST_INCLUDE_DIR=/snap/$SNAPCRAFT_PROJECT_NAME/current/share/$SNAPCRAFT_PROJECT_NAME/include
    source: https://github.com/lbellonda/qxmledit.git
    source-depth: 50
    build-packages:
      - build-essential
      - libgl1-mesa-dev
      - mesa-common-dev
      - qttools5-dev-tools
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - libqt5xmlpatterns5-dev
      - libqt5opengl5-dev
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=qxmledit|Icon=\${SNAP}/meta/gui/icon.svg|' "${SNAPCRAFT_PART_INSTALL}"/snap/"${SNAPCRAFT_PROJECT_NAME}"/current/share/"${SNAPCRAFT_PROJECT_NAME}"/QXmlEdit.desktop
    stage-packages:
      - libqt5svg5
      - libqt5xmlpatterns5
      - libqt5sql5-sqlite
      - libqt5sql5-mysql
      - libglu1-mesa
      - libqt5opengl5
      - libqt5printsupport5
      - libqt5xml5
      - libgcc1
      - libqt5core5a
      - libqt5gui5
      - libqt5widgets5
      - libstdc++6
      - zlib1g
    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/current: /
  desktop-qt5:
